name: 'Sphinx Build'
description: 'Builds documentation using Sphinx'
author: 'Wouter Kayser'
branding:
  icon: 'book'
  color: 'yellow'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.py
      shell: bash
